
apiVersion: v1
kind: Service
metadata:
  name: peer1org1-assettransfer-ccaas
  namespace: dummy-com
spec:
  type: ClusterIP
  selector:
    chaincode: peer1-org1-chaincode-demo
  ports:
  - name: "listen"
    port: 9999
    protocol: TCP
    targetPort: 9999
