
apiVersion: v1
kind: Service
metadata:
  name: peer0org3-assettransfer-ccaas
  namespace: dummy-com
spec:
  type: ClusterIP
  selector:
    chaincode: peer0-org3-chaincode-demo
  ports:
  - name: "listen"
    port: 9999
    protocol: TCP
    targetPort: 9999
